name = "cameramini-cf"
main = "src/index.js"
compatibility_date = "2026-03-01"

assets = { directory = "./public", binding = "ASSETS" }

[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "hihi"
JWT_SECRET_KEY = "tuancamera_admin_jwt_secret_key_2026_fixed_safe"

[[d1_databases]]
binding = "DB"
database_name = "cameramini_db"
database_id = "68ba7ecf-b4ea-4f22-b893-32c0f0f13ef5"
